My_Second_Project/My_Second_Project/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

My_Second_Project/classbasedview/Class_app/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from Class_app import views

app_name = 'class_app'

urlpatterns = [
    path('', views.IndexView.as_view(), name="viewindex" ),
    path('detailsview/<pk>/', views.MoreInfo.as_view(), name='details'),
    path('add_person/', views.AddPerson.as_view(), name='add_person'),
    path('update_person/<pk>/', views.UpdatePerson.as_view(), name='add_person'),
    path('delete_person/<pk>/', views.DeletePerson.as_view(), name='delete_person'),
]

My_Second_Project/classbasedview/classbasedview/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Class_app.urls')),
]

My_Second_Project/Login_app/models.py
from django.db import models

# Create your models here.

My_Second_Project/classbasedview/Class_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Person(models.Model):
    SHIRT_SIZES = [
        ('s', 'small'),
        ('m', 'medium'),
        ('l', 'large')
    ]
    name = models.CharField(max_length=42)
    email = models.EmailField(max_length=75)
    shirt_size = models.CharField(max_length=1, choices=SHIRT_SIZES)

    class Meta:
        db_table = "Person"

    def get_absolute_url(self):
        return reverse('class_app:details', kwargs={'pk':self.pk})

    def __str__(self):
        return self.name 
    
    

My_Second_Project/Login_app/views.py
from django.shortcuts import render

# Create your views here.

My_Second_Project/classbasedview/Class_app/views.py
from typing import Any, Dict
from django.shortcuts import render
from django.http import HttpResponse
from Class_app.models import Person
from django.views.generic import View, TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
# Create your views here.


class IndexView(ListView):
    context_object_name = 'person_list'
    model = Person
    template_name = 'Class_app/index.html'

class MoreInfo(DetailView):
    context_object_name = 'person'
    model = Person
    template_name = 'Class_app/detailview.html'

class AddPerson(CreateView):
    model = Person
    fields = ('name', 'email', 'shirt_size')
    template_name = 'Class_app/person_form.html'

class UpdatePerson(UpdateView):
    model = Person
    fields = ('shirt_size',)
    template_name = 'Class_app/person_form.html'

class DeletePerson(DeleteView):
    context_object_name = 'person'
    model = Person
    success_url = reverse_lazy("class_app:viewindexcd")
    template_name = 'Class_app/delete_person.html'

My_Second_Project/classbasedview/Class_app/templates/Class_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</head>
<body>
  <div>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">ClassBasedView</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'class_app:viewindex' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'class_app:add_person' %}">Add Person</a>
            </li>
          </ul>
        </div>
      </nav>
      
      <div class="container">
        {% block body_block %}
        
        {% endblock %}
      </div>
      
    </div>
</body>
</html>

My_Second_Project/classbasedview/Class_app/templates/Class_app/delete_person.html
{% extends 'Class_app/base.html' %}
{% block body_block %}
<h1>Delete {{person.name}}? </h1>
<form method="POST">
   {% csrf_token %}
  <input type="submit" value="Delete" name="submit" class="btn btn-danger btn-sm">
  <a href="{% url 'class_app:details' pk=person.pk %}" class="btn btn-info btn-sm">Cancel</a>
</form>
{% endblock %}

My_Second_Project/classbasedview/Class_app/templates/Class_app/detailview.html
{% extends 'Class_app/base.html' %}
{% block body_block %}
<h1>Person Details:</h1>
<p>{{person.name}}</p>
<p>{{person.email}}</p>
<p>{{person.shirt_size}}</p>
<a href="{% url 'class_app:add_person' pk=person.pk %}" class="btn btn-info">Update</a>
<a href="{% url 'class_app:delete_person' pk=person.pk %}" class="btn btn-danger">Delete</a>

{% endblock %}

My_Second_Project/classbasedview/Class_app/templates/Class_app/index.html
{% extends 'Class_app/base.html' %}
{% block body_block %}
<ul>
{% for person in person_list %}
<li><a href="{% url 'class_app:details' pk=person.pk %}">{{ person.name }}</a>></li>
{% endfor %}
</ul>
{% endblock %}

My_Second_Project/classbasedview/Class_app/templates/Class_app/person_form.html
{% extends 'Class_app/base.html' %}
{% block body_block %}
{% if form.instance.pk %}
<h1>Update Person</h1>
{% else %}
<h1>Add Person</h1>
{% endif %}
<form method="POST">
{{form.as_p}}{% csrf_token %}
<input type="submit" name="submit" value="Add" class="btn btn-sm btn-primary">
</form>
{% endblock%}